image: ubuntu:latest

before_script:
  - apt-get update
  - apt-get -yq install software-properties-common
  - add-apt-repository -y ppa:deadsnakes/ppa
  - apt-get -yq install python3.8 python3.8-dev python3.8-distutils python3.8-apt
  - apt install ffmpeg curl wget git fonts-open-sans imagemagick -y
  - test -e get-pip.py || wget https://bootstrap.pypa.io/get-pip.py 
  - test -e imgur.sh || wget https://raw.githubusercontent.com/tremby/imgur.sh/main/imgur.sh # imgur upload script
  - python3.8 get-pip.py
  - pip3.8 install gdown
  - pip3.8 install pytest
  - pip3.8 install -r requirements.txt
  - export VRE_WEIGHTS_DIR=`pwd`/weights
  - export PYTHONPATH="$PYTHONPATH:`pwd`"

test_run_imgur:
  script:
  - test -e DJI_0956_720p.MP4 || gdown https://drive.google.com/uc?id=158U-W-Gal6eXxYtS1ca1DAAxHvknqwAk # video
  - mkdir -p weights
  - cd weights
  - test -e  DJI_0956_velocities.npz || gdown https://drive.google.com/uc?id=1yafmmiHGMsgX6ym9Pbx2X2OxJtCY1xrT # velocities
  - test -e safeuav_semantic_0956.pkl || gdown https://drive.google.com/uc?id=1tgni1GnshQq_zCqjreBxHropRfKBQ2HH # semantic net pytorch
  - cd ..
  - test -e cfg.yaml || wget https://pastebin.com/raw/D0awQLZP -O cfg.yaml # cfg
  - X=$(shuf -i 1-9000 -n 1)
  - python3.8 main.py --videoPath DJI_0956_720p.MP4 --cfgPath cfg.yaml --outputDir test --outputResolution 240,426 --startFrame $X --endFrame $((X+1))
  - chmod +x imgur.sh
  - convert -resize 50% test/collage/$X.png test/collage/$X.png
  - bash imgur.sh test/collage/$X.png

unit_tests:
  script:
  - cd test/
  - python3.8 -m pytest .
