image: meehai/vre-ci:latest

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID && '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always
    - when: never

before_script:
  - export VRE_ROOT=`pwd`
  - export VRE_WEIGHTS_DIR=$VRE_ROOT/resources/weights
  - export PYTHONPATH="$PYTHONPATH:$VRE_ROOT"
  - export PATH="$PATH:$VRE_ROOT/bin"
  # this is because we are unable to maintain a library properly
  - pip uninstall -y media-processing-lib
  - python3 -m pip install -r requirements.txt

pylint:
  script:
    - pip install pylint
    - python -m pylint --rcfile=.pylintrc $(git ls-files "*.py" | grep -v "test/\|examples/")

test_end_to_end_imgur:
  script:
    - bash test/end_to_end/imgur/run.sh

unit_tests:
  script:
    - python3 -m pytest test/unit

integration_tests:
  script:
    - python3 -m pytest test/integration
