image: python:3.9-bullseye

before_script:
  - apt-get update
  - apt-get install git -y
  - apt install ffmpeg curl wget git fonts-open-sans imagemagick -y
  - test -e get-pip.py || wget https://bootstrap.pypa.io/get-pip.py 
  - test -e ci_imgur/imgur.sh || wget https://raw.githubusercontent.com/tremby/imgur.sh/main/imgur.sh -O ci_imgur/imgur.sh # imgur upload script
  - chmod +x ci_imgur/imgur.sh
  - chmod +X ci_imgur/ci.sh
  - python3 get-pip.py
  - pip3 install gdown
  - pip3 install pytest
  - pip3 install -r requirements.txt
  - export VRE_WEIGHTS_DIR=`pwd`/weights
  - export PYTHONPATH="$PYTHONPATH:`pwd`"

test_run_imgur:
  script:
  - cd ci_imgur
  - bash ci.sh

unit_tests:
  script:
  - cd test/
  - python3 -m pytest .
