image: python:3.11-bullseye

variables:
  GIT_LFS_SKIP_SMUDGE: "1"

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
    when: always
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
    when: always
  - when: never

before_script:
  - apt-get update
  - apt-get install -y ffmpeg fonts-open-sans graphviz
  - export VRE_ROOT=`pwd`
  - export VRE_WEIGHTS_DIR=$VRE_ROOT/weights
  - export VRE_LOGLEVEL=3
  - export PYTHONPATH="$PYTHONPATH:$VRE_ROOT"
  - export PATH="$PATH:$VRE_ROOT/cli"
  - cat requirements.txt | sed "s/torch==2.5.1/torch @ https:\/\/download.pytorch.org\/whl\/cpu\/torch-2.5.1%2Bcpu-cp311-cp311-linux_x86_64.whl/g" | sed "s/torchvision==0.20.1/torchvision @ https:\/\/download.pytorch.org\/whl\/cpu\/torchvision-0.20.1%2Bcpu-cp311-cp311-linux_x86_64.whl/g" > /tmp/requirements_ci.txt
  - pip install -r /tmp/requirements_ci.txt
  - pip install pylint==3.2.7 pytest pytest-rerunfailures
  - pip install sphinx sphinx_rtd_theme myst-parser

pages:
  script:
    - bash docs/makedocs.sh
  publish: docs/build/html
  artifacts:
    paths:
      - docs/build/html
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

pylint:
  script:
    - python -m pylint --rcfile=.pylintrc $(git ls-files "*.py" | grep -v "test/\|examples/")

vre_unit_integration:
  script:
    - python3 -m pytest test/vre

vre_repository_unit:
  script:
    - python3 -m pytest test/vre_repository/unit

vre_repository_integration:
  script:
    - python3 -m pytest test/vre_repository/integration

vre_repository_e2e_imgur:
  script:
    - bash test/vre_repository/end_to_end/imgur/run.sh

vre_repository_e2e_task_mapped:
  script:
    - bash test/vre_repository/end_to_end/task_mapped_representations/run.sh
