stages:
  - test

test:
  stage: test
  image: ubuntu:latest
  script:
  - apt-get update
  - apt-get -yq install software-properties-common
  - add-apt-repository -y ppa:deadsnakes/ppa
  - apt-get -yq install python3.8 python3.8-dev python3.8-distutils python3.8-apt
  - apt install curl wget -y
  - wget https://bootstrap.pypa.io/get-pip.py 
  - python3.8 get-pip.py
  - pip3.8 install gdown
  - pip3.8 install -r requirements.txt
  - gdown https://drive.google.com/uc?id=158U-W-Gal6eXxYtS1ca1DAAxHvknqwAk # video
  - mkdir -p weights
  - export VRE_WEIGHTS_DIR=`pwd`/weights
  - cd weights
  - gdown https://drive.google.com/uc?id=1ibvAcRgdPLXHL_NBrXwNu1uks8DpJUc4 # logs
  - gdown https://drive.google.com/uc?id=1tgni1GnshQq_zCqjreBxHropRfKBQ2HH # semantic net
  - cd ..
  - wget https://pastebin.com/raw/D0awQLZP -O cfg.yaml # cfg
  - python3 main.py --videoPath DJI_0956_720p.MP4 --cfgPath cfg.yaml --outputDir test --outputResolution 240,426 --startFrame 1000 --endFrame 1001
  - wget https://raw.githubusercontent.com/tremby/imgur.sh/main/imgur.sh # imgur upload script
  - chmod +x imgur.sh
  - convert -resize 50% test/collage/1000.png test/collage/1000.png
  - bash imgur.sh test/collage/1000.png
