image: python:3.11-bullseye

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
    when: always
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
    when: always
  - when: never

before_script:
  - apt-get update
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
  - apt-get install -y iproute2 ffmpeg fonts-open-sans vim git-lfs
  - export VRE_ROOT=`pwd`
  - export VRE_LOGS_DIR=$VRE_ROOT/logs
  - export VRE_LOGLEVEL=3
  - export PYTHONPATH="$PYTHONPATH:$VRE_ROOT"
  - export PATH="$PATH:$VRE_ROOT/bin"
  - cat requirements.txt | sed "s/torch==2.4.1/torch @ https:\/\/download.pytorch.org\/whl\/cpu\/torch-2.4.1%2Bcpu-cp311-cp311-linux_x86_64.whl/g" | sed "s/torchvision==0.19.1/torchvision @ https:\/\/download.pytorch.org\/whl\/cpu\/torchvision-0.19.1%2Bcpu-cp311-cp311-linux_x86_64.whl/g" > /tmp/requirements_ci.txt
  - pip install -r /tmp/requirements_ci.txt
  - pip install pylint==3.2.7 pytest
  - git lfs pull

pylint:
  script:
    - python -m pylint --rcfile=.pylintrc $(git ls-files "*.py" | grep -v "test/\|examples/")

test_end_to_end_imgur:
  script:
    - bash test/end_to_end/imgur/run.sh

unit_tests:
  script:
    - python3 -m pytest test/unit

integration_tests:
  script:
    - python3 -m pytest test/integration
