image: meehai/vre-ci:latest

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
    when: always
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
    when: always
  - when: never

before_script:
  - export VRE_ROOT=`pwd`
  - export VRE_WEIGHTS_DIR=$VRE_ROOT/resources/weights
  - export VRE_LOGLEVEL=3
  - export PYTHONPATH="$PYTHONPATH:$VRE_ROOT"
  - export PATH="$PATH:$VRE_ROOT/bin"
  - python3 -m pip install -r requirements.txt

pylint:
  script:
    - pip install pylint==3.2.7
    - python -m pylint --rcfile=.pylintrc $(git ls-files "*.py" | grep -v "test/\|examples/")

test_end_to_end_imgur:
  script:
    - bash test/end_to_end/imgur/run.sh

unit_tests:
  script:
    - python3 -m pytest test/unit

integration_tests:
  script:
    - mkdir -p $VRE_WEIGHTS_DIR && gdown https://drive.google.com/uc?id=1yafmmiHGMsgX6ym9Pbx2X2OxJtCY1xrT -O $VRE_WEIGHTS_DIR/DJI_0956_velocities.npz
    - python3 -m pytest test/integration
