#!/usr/bin/env python3
import sys
import subprocess
import signal
from argparse import ArgumentParser, Namespace, REMAINDER
import torch
from vre import FFmpegVideo

def _cleanup(signum, frame):
    print("Terminating subprocesses...")
    for p in processes:
        p.terminate()
    sys.exit(1)

def get_args() -> Namespace:
    """Argument parsing"""
    parser = ArgumentParser(description="Distribute VRE processing across multiple GPUs")
    parser.add_argument("video_file", type=str, help="Path to the video file")
    parser.add_argument("--gpus", nargs="+", help="List of GPU indices to use", type=int, default=[])
    parser.add_argument("--frames", type=str, help="Frame range in the format 'start..end'")
    parser.add_argument("vre_args", nargs="+", help="Additional arguments to pass to VRE")
    args = parser.parse_args()
    assert len(args.gpus) > 0, args.gpus
    assert max(args.gpus) < (n := torch.cuda.device_count()), f"{args.gpus} vs. {n} available"
    return args

def main(args: Namespace):
    """main fn"""
    signal.signal(signal.SIGINT, _cleanup)
    signal.signal(signal.SIGTERM, _cleanup)

    video_file = args.video_file
    gpu_indices = list(map(str, args.gpus))
    n_gpus = len(gpu_indices)
    video = FFmpegVideo(video_file)

    if args.frames:
        start_frame, end_frame = map(int, args.frames.split(".."))
    else:
        start_frame, end_frame = 0, len(video)

    total_frames = end_frame - start_frame
    frames_per_gpu = total_frames // n_gpus

    processes = []
    for i, gpu in enumerate(gpu_indices):
        gpu_start_frame = start_frame + i * frames_per_gpu
        gpu_end_frame = gpu_start_frame + frames_per_gpu
        
        # Ensure the last partition captures all remaining frames
        if i == n_gpus - 1:
            gpu_end_frame = end_frame
        
        env = {"CUDA_VISIBLE_DEVICES": gpu, "VRE_DEVICE": "cuda"}
        cmd = ["vre", video_file, "--frames", f"{gpu_start_frame}..{gpu_end_frame}"] + args.vre_args
        
        env_str = " ".join([f"{k}={v}" for k, v in env.items()])
        print(f"Executing command: {env_str} {' '.join(cmd)}")
        
        process = subprocess.Popen(cmd, env=env)
        processes.append(process)

    # Wait for all processes to complete
    for p in processes:
        p.wait()

if __name__ == "__main__":
    main(get_args())
