#!/usr/bin/env python3
"""
Generate the API reference table in README.md from the public functions of both modules.

Backend per function = which file defines it: image_utils.py -> numpy, image_utils_pil.py -> PIL,
a name in both -> both. Run from anywhere: `python .docs/build_api_reference.py`.
"""
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = {"numpy": ROOT / "image_utils.py", "PIL": ROOT / "image_utils_pil.py"}
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN API REFERENCE (generated by .docs/build_api_reference.py) -->"
END = "<!-- END API REFERENCE -->"


def _typed(arg: ast.arg) -> str:
    """`name: Type`, or just `name` when unannotated."""
    return f"{arg.arg}: {ast.unparse(arg.annotation)}" if arg.annotation else arg.arg


def params(fn: ast.FunctionDef) -> list[str]:
    """`name: Type` for every parameter, including *args / **kwargs."""
    a = fn.args
    out = [_typed(arg) for arg in a.posonlyargs + a.args]
    if a.vararg:
        out.append("*" + _typed(a.vararg))
    out += [_typed(arg) for arg in a.kwonlyargs]
    if a.kwarg:
        out.append("**" + _typed(a.kwarg))
    return out


def ret_type(fn: ast.FunctionDef) -> str:
    """the return annotation as text, or empty string."""
    return ast.unparse(fn.returns) if fn.returns else ""


def doc_line(fn: ast.FunctionDef) -> str:
    """first line of the docstring, or empty string."""
    lines = (ast.get_docstring(fn) or "").splitlines()
    return lines[0] if lines else ""


def public_functions(path: Path) -> dict[str, ast.FunctionDef]:
    """public (no leading _) top-level functions, in source order."""
    tree = ast.parse(path.read_text())
    return {n.name: n for n in tree.body if isinstance(n, ast.FunctionDef) and not n.name.startswith("_")}


def collect() -> list[tuple[str, list[str], str, str, str]]:
    """(name, typed params, return type, docstring, backend) rows: numpy funcs first, then PIL-only."""
    fns = {b: public_functions(p) for b, p in SOURCES.items()}
    numpy_fns, pil_fns = fns["numpy"], fns["PIL"]
    rows = [(name, params(fn), ret_type(fn), doc_line(fn), "both" if name in pil_fns else "numpy")
            for name, fn in numpy_fns.items()]
    rows += [(name, params(fn), ret_type(fn), doc_line(fn), "PIL")
             for name, fn in pil_fns.items() if name not in numpy_fns]
    return rows


def _esc(text: str) -> str:
    """escape pipes so they don't split markdown table columns (needed even inside code spans)."""
    return text.replace("|", "\\|")


def table(rows: list[tuple[str, list[str], str, str, str]]) -> str:
    """Function | Parameters (typed, one per line + return) | Description | Backend."""
    lines = ["| Function | Parameters | Description | Backend |", "| --- | --- | --- | --- |"]
    for name, param_lines, ret, doc, backend in rows:
        cells = [f"`{_esc(p)}`" for p in param_lines]
        if ret:
            cells.append(f"→ `{_esc(ret)}`")
        lines.append(f"| `{name}` | {'<br>'.join(cells)} | {_esc(doc)} | {backend} |")
    return "\n".join(lines)


def main():
    """regenerate the API reference table between the markers in README.md (append if missing)."""
    block = f"{BEGIN}\n## API reference\n\n{table(collect())}\n{END}"
    text = README.read_text()
    if BEGIN in text and END in text:
        pre, rest = text.split(BEGIN, 1)
        text = pre + block + rest.split(END, 1)[1]
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    README.write_text(text)
    print(f"Wrote {sum(1 for _ in collect())} functions to {README.relative_to(ROOT)}")
    print("\n" + table(collect()))


if __name__ == "__main__":
    main()
