default_compute_parameters:
  output_size: [540, 960]
  batch_size: 1

default_io_parameters:
  binary_format: npz
  image_format: png
  compress: True

default_learned_parameters:
  device: ${oc.env:VRE_DEVICE,cpu}

representations:
  rgb:
    type: default/rgb
    dependencies: []
    parameters: {}
    compute_parameters:
      batch_size: 5

  opticalflow_rife:
    type: optical-flow/rife
    dependencies: []
    parameters:
      uhd: False
      compute_backward_flow: False

  normals_svd(depth_marigold):
    type: normals/depth-svd
    dependencies: [depth_marigold]
    parameters:
      sensor_fov: 75
      sensor_width: 3840
      sensor_height: 2160
      window_size: 11
    compute_parameters:
      output_dtype: float16

  semantic_mask2former_mapillary_49189528_0:
    type: semantic-segmentation/mask2former
    dependencies: []
    parameters:
      model_id: "49189528_0"
      semantic_argmax_only: True

  semantic_mask2former_coco_47429163_0:
    type: semantic-segmentation/mask2former
    dependencies: []
    parameters:
      model_id: "47429163_0"
      semantic_argmax_only: True

  depth_marigold:
    type: depth/marigold
    dependencies: []
    parameters:
      variant: marigold-lcm-v1-0
      denoising_steps: 1
      ensemble_size: 1
      processing_resolution: 768
